name: torrento
description: An API wrapper for multiple torrent clients to remotely control torrents
version: 0.1.6
homepage: https://github.com/nateshmbhat/torrento

dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+2
  meta: ^1.1.8

dev_dependencies:
  test: ^1.11.0

environment:
  sdk: '>=1.20.1 <3.0.0'